# Some bits taken from https://gist.github.com/ndarville/3625246

sudo: false
dist: xenial
language: python

python:
    - "3.6"
    - "3.7"
    - "3.8"

services: postgresql

addons:
    postgresql: "9.6"

env:
    - DJANGO_VERSION=2.2.6

install:
    - pip install -r requirements.txt

before_script:
    - psql -U postgres -c 'create database travisdb;'

script:
    - SECRET_KEY=testkey DATABASE_URL='postgres://localhost/travisdb' python manage.py test -v2
