# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 19:52
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import fleetcore.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FleetUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leadering', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'users',
                'verbose_name': 'user',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_filename', models.CharField(blank=True, max_length=512, null=True)),
                ('billing_date', models.DateField(blank=True, null=True)),
                ('billing_total', fleetcore.fields.MoneyField(decimal_places=3, default=Decimal('0'), max_digits=10)),
                ('billing_debt', fleetcore.fields.MoneyField(decimal_places=3, default=Decimal('0'), max_digits=10)),
                ('parsing_date', models.DateTimeField(blank=True, null=True)),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('provider_number', models.CharField(blank=True, max_length=50)),
                ('internal_tax', fleetcore.fields.TaxField(decimal_places=5, default=Decimal('0.0417'), max_digits=6, validators=[fleetcore.fields.validate_tax])),
                ('iva_tax', fleetcore.fields.TaxField(decimal_places=5, default=Decimal('0.27'), max_digits=6, validators=[fleetcore.fields.validate_tax])),
                ('other_tax', fleetcore.fields.TaxField(decimal_places=5, default=Decimal('0.04'), max_digits=6, validators=[fleetcore.fields.validate_tax])),
                ('notes', models.TextField(blank=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_user', models.CharField(blank=True, max_length=500, verbose_name='Usuario')),
                ('reported_plan', models.CharField(blank=True, max_length=5, verbose_name='Plan oficial')),
                ('monthly_price', fleetcore.fields.MoneyField(decimal_places=3, default=Decimal('0'), max_digits=10, verbose_name='Precio del plan ($)')),
                ('services', fleetcore.fields.MoneyField(decimal_places=3, default=Decimal('0'), max_digits=10, verbose_name='Cargos y servicios ($)')),
                ('refunds', fleetcore.fields.MoneyField(decimal_places=3, default=Decimal('0'), max_digits=10, verbose_name='Reintegros ($)')),
                ('included_min', fleetcore.fields.MinuteField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Minutos consumidos incluidos en plan')),
                ('exceeded_min', fleetcore.fields.MinuteField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Minutos consumidos fuera del plan')),
                ('exceeded_min_price', fleetcore.fields.MoneyField(decimal_places=3, default=Decimal('0'), max_digits=10, verbose_name='Minutos consumidos fuera del plan ($)')),
                ('ndl_min', fleetcore.fields.MinuteField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Discado nacional (minutos)')),
                ('ndl_min_price', fleetcore.fields.MoneyField(decimal_places=3, default=Decimal('0'), max_digits=10, verbose_name='Discado nacional ($)')),
                ('idl_min', fleetcore.fields.MinuteField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Discado internacional (minutos)')),
                ('idl_min_price', fleetcore.fields.MoneyField(decimal_places=3, default=Decimal('0'), max_digits=10, verbose_name='Discado internacional ($)')),
                ('sms', fleetcore.fields.SMSField(default=0, verbose_name='Mensajes consumidos')),
                ('sms_price', fleetcore.fields.MoneyField(decimal_places=3, default=Decimal('0'), max_digits=10, verbose_name='Mensajes consumidos ($)')),
                ('equipment_price', fleetcore.fields.MoneyField(decimal_places=3, default=Decimal('0'), max_digits=10, verbose_name='Equipos ($)')),
                ('other_price', fleetcore.fields.MoneyField(decimal_places=3, default=Decimal('0'), max_digits=10, verbose_name='Varios ($)')),
                ('reported_total', fleetcore.fields.MoneyField(decimal_places=3, default=Decimal('0'), max_digits=10, verbose_name='Total ($)')),
                ('penalty_min', fleetcore.fields.MinuteField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Multa de minutos')),
                ('penalty_sms', fleetcore.fields.SMSField(default=0, verbose_name='Multa de mensajes')),
                ('mins', fleetcore.fields.MinuteField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Suma de minutos consumidos y excedentes, antes de multas')),
                ('total_before_taxes', fleetcore.fields.MoneyField(decimal_places=3, default=Decimal('0'), max_digits=10)),
                ('taxes', fleetcore.fields.TaxField(decimal_places=5, default=Decimal('0'), max_digits=6, validators=[fleetcore.fields.validate_tax])),
                ('total_before_round', fleetcore.fields.MoneyField(decimal_places=3, default=Decimal('0'), max_digits=10)),
                ('total', fleetcore.fields.MoneyField(decimal_places=3, default=Decimal('0'), max_digits=10)),
                ('extra', fleetcore.fields.MoneyField(decimal_places=3, default=Decimal('0'), max_digits=10, verbose_name='Extra (por equipo/s, o IVA de equipo, etc.)')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleetcore.Bill')),
            ],
            options={
                'get_latest_by': 'bill__billing_date',
            },
        ),
        migrations.CreateModel(
            name='DataPack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kbs', models.PositiveIntegerField(blank=True, null=True)),
                ('price', fleetcore.fields.MoneyField(decimal_places=3, default=Decimal('0'), max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('provider', models.CharField(max_length=256)),
                ('report_consumption_template', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', fleetcore.fields.MinuteField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('sms', fleetcore.fields.SMSField(default=0)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleetcore.Bill')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('active_since', models.DateTimeField(default=django.utils.timezone.now)),
                ('active_to', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'get_latest_by': 'active_since',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', fleetcore.fields.MoneyField(decimal_places=3, default=Decimal('0'), max_digits=10)),
                ('price_min', fleetcore.fields.MoneyField(decimal_places=3, default=Decimal('0'), max_digits=10)),
                ('price_sms', fleetcore.fields.MoneyField(decimal_places=3, default=Decimal('0'), max_digits=10)),
                ('included_min', models.PositiveIntegerField(default=0)),
                ('included_sms', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('with_min_clearing', models.BooleanField(default=True)),
                ('with_sms_clearing', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SMSPack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', fleetcore.fields.SMSField(default=0)),
                ('price', fleetcore.fields.MoneyField(decimal_places=3, default=Decimal('0'), max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='phone',
            name='current_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleetcore.Plan'),
        ),
        migrations.AddField(
            model_name='phone',
            name='data_pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fleetcore.DataPack'),
        ),
        migrations.AddField(
            model_name='phone',
            name='sms_pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fleetcore.SMSPack'),
        ),
        migrations.AddField(
            model_name='phone',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='penalty',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleetcore.Plan'),
        ),
        migrations.AddField(
            model_name='consumption',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleetcore.Phone'),
        ),
        migrations.AddField(
            model_name='consumption',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleetcore.Plan'),
        ),
        migrations.AddField(
            model_name='bill',
            name='fleet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleetcore.Fleet'),
        ),
        migrations.AlterUniqueTogether(
            name='penalty',
            unique_together=set([('bill', 'plan')]),
        ),
        migrations.AlterUniqueTogether(
            name='consumption',
            unique_together=set([('phone', 'bill')]),
        ),
    ]
