# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 00:33
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import fleetcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fleetcore', '0004_auto_20150531_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='internal_tax',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.0417'), max_digits=6, validators=fleetcore.fields.validate_tax),
        ),
        migrations.AlterField(
            model_name='bill',
            name='iva_tax',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.27'), max_digits=6, validators=fleetcore.fields.validate_tax),
        ),
        migrations.AlterField(
            model_name='bill',
            name='other_tax',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.04'), max_digits=6, validators=fleetcore.fields.validate_tax),
        ),
        migrations.AlterField(
            model_name='consumption',
            name='taxes',
            field=models.DecimalField(decimal_places=5, default=Decimal('0'), max_digits=6, validators=fleetcore.fields.validate_tax),
        ),
        migrations.AlterField(
            model_name='fleetuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.')], verbose_name='username'),
        ),
    ]
