# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-05 17:05
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations
import fleetcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fleetcore', '0005_auto_20160601_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='internal_tax',
            field=fleetcore.fields.TaxField(decimal_places=5, default=Decimal('0.0417'), max_digits=6, validators=[fleetcore.fields.validate_tax, fleetcore.fields.validate_tax, fleetcore.fields.validate_tax]),
        ),
        migrations.AlterField(
            model_name='bill',
            name='iva_tax',
            field=fleetcore.fields.TaxField(decimal_places=5, default=Decimal('0.27'), max_digits=6, validators=[fleetcore.fields.validate_tax, fleetcore.fields.validate_tax, fleetcore.fields.validate_tax]),
        ),
        migrations.AlterField(
            model_name='bill',
            name='other_tax',
            field=fleetcore.fields.TaxField(decimal_places=5, default=Decimal('0.04'), max_digits=6, validators=[fleetcore.fields.validate_tax, fleetcore.fields.validate_tax, fleetcore.fields.validate_tax]),
        ),
        migrations.AlterField(
            model_name='consumption',
            name='taxes',
            field=fleetcore.fields.TaxField(decimal_places=5, default=Decimal('0'), max_digits=6, validators=[fleetcore.fields.validate_tax, fleetcore.fields.validate_tax, fleetcore.fields.validate_tax]),
        ),
    ]
