# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 19:35
from __future__ import unicode_literals

from decimal import Decimal
import django.contrib.auth.validators
from django.db import migrations, models
import fleetcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fleetcore', '0006_auto_20170305_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='internal_tax',
            field=fleetcore.fields.TaxField(decimal_places=5, default=Decimal('0.0417'), max_digits=6, validators=[fleetcore.fields.validate_tax, fleetcore.fields.validate_tax, fleetcore.fields.validate_tax]),
        ),
        migrations.AlterField(
            model_name='bill',
            name='iva_tax',
            field=fleetcore.fields.TaxField(decimal_places=5, default=Decimal('0.27'), max_digits=6, validators=[fleetcore.fields.validate_tax, fleetcore.fields.validate_tax, fleetcore.fields.validate_tax]),
        ),
        migrations.AlterField(
            model_name='bill',
            name='other_tax',
            field=fleetcore.fields.TaxField(decimal_places=5, default=Decimal('0.04'), max_digits=6, validators=[fleetcore.fields.validate_tax, fleetcore.fields.validate_tax, fleetcore.fields.validate_tax]),
        ),
        migrations.AlterField(
            model_name='consumption',
            name='taxes',
            field=fleetcore.fields.TaxField(decimal_places=5, default=Decimal('0'), max_digits=6, validators=[fleetcore.fields.validate_tax, fleetcore.fields.validate_tax, fleetcore.fields.validate_tax]),
        ),
        migrations.AlterField(
            model_name='fleetuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
